sudo: false
language: python
python:
  - "2.7"
  - "3.6"
env:
  - TOXENV=py27
  - TOXENV=py36
  - TOXENV=pypy
matrix:
  allow_failures:
    - env: TOXENV=pypy
install:
  - pip install tox
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls
