sudo: false
language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27,meta
    - python: 3.6
      env: TOXENV=py36,meta
    - python: pypy
      env: TOXENV=pypy
  allow_failures:
    - env: TOXENV=pypy

install:
  - pip install tox
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls
